version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nocturne-auth-server-db
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=47dfb729-a25c-4988-997d-ffb8a90a3f1c
    network_mode: host

  admin:
    build:
      context: .
      dockerfile: src/Admin/Dockerfile
    depends_on:
      - db
      - server
    image: nocturne-auth-server/admin
    container_name: nocturne-auth-server-admin
    volumes:
      - ./certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:34560;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=4fd08b7e-0777-406d-97b9-734bc1515124
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/admin.pfx
      - DatabaseConnections__Main__Host=localhost,1433
      - Authorization__Authority=https://localhost:61767
      - Authorization__DangerousAcceptAnyCertificate=true
      - Initialize=true
    network_mode: host

  server:
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    depends_on:
      - db
    image: nocturne-auth-server/server
    container_name: nocturne-auth-server-openid-provider
    volumes:
      - ./certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:61767;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=9286bf83-89c4-4617-98bf-ae529f3ec300
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/server.pfx
      - DatabaseConnections__Main__Host=localhost,1433
    network_mode: host

  email:
    image: rnwood/smtp4dev:v3
    container_name: nocturne-auth-server-email
    volumes:
      - ./emails:/smtp4dev
    environment:
      - Kestrel__Endpoints__Http__Url=http://localhost:34564
      - ServerOptions__HostName=localhost
      - ServerOptions__Port=587
    network_mode: host
