services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nocturne-auth-server-db
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=47dfb729-a25c-4988-997d-ffb8a90a3f1c

  email:
    image: rnwood/smtp4dev:v3
    container_name: nocturne-auth-server-email
    ports:
      - 34564:80
    volumes:
      - ./emails:/smtp4dev
    environment:
      - ServerOptions__HostName=localhost
      - ServerOptions__Port=587
