name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    name: 'Build (Server)'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.202'

    - name: Build
      run: dotnet build

  build-web:
    name: 'Build (Web)'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Build vendor packages
      run: npm run vendor
